title: Asmijana's Personal Website
description: Welcome to my Jekyll-powered personal site!
theme: minima  # Replace "minima" with another theme name if you prefer
# Optional: add your GitHub username for social links
github_username: asmijana
